name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip yarn ipywidgets=7.6 jupyterlab=3 pytest nbval

    - name: Install sidecar
      shell: bash -l {0}
      run: pip install -ve .

    - name: Check installation files
      shell: bash -l {0}
      run: |
        test -d $CONDA_PREFIX/share/jupyter/labextensions/@jupyter-widgets/jupyterlab-sidecar
        test -f $CONDA_PREFIX/share/jupyter/labextensions/@jupyter-widgets/jupyterlab-sidecar/package.json

    - name: Check labextension
      shell: bash -l {0}
      run: jupyter labextension list 2>&1 | grep -ie "@jupyter-widgets/jupyterlab-sidecar.*enabled.*ok" -

    - name: Run notebooks
      shell: bash -l {0}
      run: pytest .
